name: Compile LaTeX Document
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: danteev/texlive:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Configure TeX Live mirror and update
        run: |
          tlmgr option repository https://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/texlive/tlnet
          tlmgr update --self
          tlmgr update --all
          tlmgr --version
          
      - name: Install fonts
        run: |
          tlmgr install fandol
          
      - name: Compile LaTeX document 
        run: |
          cd "Problem Solutions(Fu Qiang)"
          latexmk -xelatex -interaction=nonstopmode -file-line-error "Problem Solutions(Fu Qiang).tex"
          
      - name: Upload the generated PDF
        uses: actions/upload-artifact@v4
        with:
          name: Problem-Solutions-Fu-Qiang-PDF
          path: "Problem Solutions(Fu Qiang)/Problem Solutions(Fu Qiang).pdf"
