name: Compile LaTeX Document
on: [push]  

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: danteev/texlive:latest  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Compile LaTeX document
        run: |
          latexmk -pdf -interaction=nonstopmode -file-line-error main.tex
          
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: main.pdf
